name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter (via FVM)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install FVM
        run: |
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install Flutter SDK via FVM
        run: |
          fvm install 3.13.9
          fvm use 3.13.9

      - name: Get dependencies
        run: fvm flutter pub get

      - name: Build APK
        run: fvm flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
